apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-task-ingress

spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: gettask.devops-engineer-adda.store
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: get-tasks
            port: 
              number: 80
