name: Build & Push Docker Image to ACR

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: gettasktodo
  IMAGE_TAG: v1
  ACR_NAME: acrsumit22
  ACR_LOGIN_SERVER: acrsumit22.azurecr.io

jobs:
  build_and_push:  #job id
    name: build and push #job name
    runs-on: ubuntu-latest #runner and tag dena padta h
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}



    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
    
    - name: Tag Docker Image for ACR
      run: |
        docker tag  $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
      
    - name: Push Docker image to ACR
      run: |
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG 


